### ISSUE TITLE
Error: Cannot find module 'boilerpipe'

### ISSUE THREAD

**Issue by acardinale** [xissy/node-boilerpipe#1]
I installed node-java
node install -g java
and boilerpipe
node install -g boilerpipe

but if I run
node mytest-boilerpipe.js

it shows this error
Error: Cannot find module 'boilerpipe'

**Comment by xissy** [comment]
Can you copy & paste your `mytest-boilerpipe.js` here?

**Comment by acardinale** [comment]
var Boilerpipe = require('boilerpipe');

var boilerpipe = new Boilerpipe({
    extractor: Boilerpipe.Extractor.Article,
    url: 'http://www.andrea-cardinale.it/web-marketing/webreevolution-2013-ci-saro-anche-io.html'
  });

boilerpipe.getText(function(err, text) {
    console.log(text);
});

**Comment by xissy** [comment]
It seems okay with your source code.

But I saw that you had written `node install xxx` instead of `npm install xxx`. You should use `npm` to install modules.

Would you check this?

**Comment by acardinale** [comment]
Sorry, I wrong to write, i used
npm install -g java
and
npm install -g boilerpipe

npm list shows this

npm list
├─┬ boilerpipe@0.0.2
│ ├── async@0.2.9
│ └── coffee-script@1.6.3
├── coffee-script@1.6.3
└── java@0.2.3

**Comment by acardinale** [comment]
I solved it!

coffee --compile node_modules/boilerpipe/lib/index.coffee
cp node_modules/boilerpipe/lib/index.js node_modules/boilerpipe/

I have not read anywhere this step

**Comment by xissy** [comment]
Yes, right!

There is a problem which can't access the main coffee-script file from pure javascript.
I'm mainly used to `coffee` instead of `node` so didn't know this issue.
I'll fix this and commit here and npm asap.

Thank you so much @acardinale!

**Comment by xissy** [comment]
Fixed! 4e7138f908fbd7d833702eee1b0b7a490bc763d5
